# Generated by Django 4.1.2 on 2022-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='avater',
            field=models.ImageField(default='avater.jpg', upload_to='dp'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='banner',
            field=models.ImageField(upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
