# Generated by Django 4.1.2 on 2022-10-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appinfo_avater_alter_appinfo_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='avater',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='avatar',
            field=models.ImageField(default=2, upload_to='dp'),
            preserve_default=False,
        ),
    ]
